### PR TITLE
Allow importing services from PHP and XML configuration files

### PR DESCRIPTION
**Pull request by ajgarlag**
See #10

### CODE REVIEW

**Comment by jakzal** [comment]
What's the use case? Especially for php based config? :)

**Comment by ajgarlag** [comment]
I have a new project where I've setup the services using the fluent PHP based configuration introduced in https://github.com/symfony/symfony/pull/23834.

With this format the IDE provides better code completion suggestions and I can rename classnames declared in configuration files using the Refactor feature included in the IDE.

I've added support for XML format after seeing #10

**Comment by jakzal** [comment]
Thank you for your contribution!

> With this format the IDE provides better code completion suggestions and I can rename classnames declared in configuration files using the Refactor feature included in the IDE

This depends on the IDE. Phpstorm with the Symfony plugin does a really good job for me. 

With auto wiring support and minimal amount of config you need to add, I don't see a point of using php or xml. Especially in a behat extension. Nevertheless, I can understand to some it's appealing and I'm probably gonna merge this in ;)

**Comment by jakzal** [comment]
Thank you @ajgarlag!

**Comment by jakzal** [comment]
Included in the [v2.1.0](https://github.com/jakzal/BehatNoExtension/releases/tag/v2.1.0) release.

**Comment by ajgarlag** [comment]
Thank you @jakzal for merge and quick release.

There is an error in the release note:

> Ignore development files from git export (#16) / thanks @ajgarlag

**Comment by jakzal** [comment]
@ajgarlag copy&paste is the source of all evil :P fixed!

**Pull request merged**
